name: Run Tests

on:
  push:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Run Tests
        run: |
          go test -v ./instance/...
          go test -v ./snapshot/...
